### ISSUE TITLE
[ERROR] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by iHaiduk** [CurrencyCloud/currencycloud-js#63]
Hello! I have an error when trying to create payment:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new APIerror (/usr/src/app/node_modules/currency-cloud/lib/error.js:37:45)
    at new InternalApplicationError (/usr/src/app/node_modules/currency-cloud/lib/error.js:87:1)
    at new module.exports (/usr/src/app/node_modules/currency-cloud/lib/error.js:110:14)
    at /usr/src/app/node_modules/currency-cloud/lib/client.js:125:17
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:462:21)
```

Service response:
```
StatusCodeError: 500 - ""
    at new StatusCodeError (/usr/src/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Request data:
```
{
    headers: {
      'X-Auth-Token': '7006......1d37',
      'User-Agent': 'CurrencyCloudSDK/2.0 NodeJS/4.1.0'
    },
    uri: 'https://devapi.currencycloud.com/v2/payments/create',
    method: 'POST',
    qsStringifyOptions: { arrayFormat: 'brackets' },
    form: {
      on_behalf_of: '7a3265be-dee5-4e43-be7f-49769eaf71b9',
      beneficiary_id: '675eddd7-f853-4d1f-a5f1-90886f39e43c',
      currency: 'EUR',
      amount: '1.00',
      reason: 'reason payment',
      payment_type: 'priority',
      reference: '11643750-c6db-11eb-8251-69c9c3f6281a'
    },
    qs: null,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  }
```

**Comment by jonathancouchman** [comment]
@iHaiduk can you confirm which version of the currencycloud-js SDK you are using?

**Comment by jonathancouchman** [comment]
The response body of the error from the api appears not to be well formed json in this case. The SDK does not handle this. Code updated to handle malformed response body. 

Issue of malformed response appears unrelated to the SDK, and being investigated on the backend service
